### ISSUE TITLE
run-server.sh fails with 'bundler: command not found: middleman'

### ISSUE THREAD

**Issue by booxter** [redhat-openstack/website#455] opened 2016-03-11 11:56 UTC
-bash-4.2$ ./run-server.sh 
Using i18n 0.7.0
0:  i18n (0.7.0) from /home/vagrant/.gem/ruby/specifications/i18n-0.7.0.gemspec
Using json 1.8.2
0:  json (1.8.2) from /home/vagrant/.gem/ruby/specifications/json-1.8.2.gemspec
Using minitest 5.6.0
0:  minitest (5.6.0) from /home/vagrant/.gem/ruby/specifications/minitest-5.6.0.gemspec
Using thread_safe 0.3.5
0:  thread_safe (0.3.5) from /home/vagrant/.gem/ruby/specifications/thread_safe-0.3.5.gemspec
Using tzinfo 1.2.2
0:  tzinfo (1.2.2) from /home/vagrant/.gem/ruby/specifications/tzinfo-1.2.2.gemspec
Using activesupport 4.1.10
0:  activesupport (4.1.10) from /home/vagrant/.gem/ruby/specifications/activesupport-4.1.10.gemspec
Using addressable 2.3.8
0:  addressable (2.3.8) from /home/vagrant/.gem/ruby/specifications/addressable-2.3.8.gemspec
Using asciidoctor 1.5.2
0:  asciidoctor (1.5.2) from /home/vagrant/.gem/ruby/specifications/asciidoctor-1.5.2.gemspec
Using execjs 2.5.2
0:  execjs (2.5.2) from /home/vagrant/.gem/ruby/specifications/execjs-2.5.2.gemspec
Using autoprefixer-rails 5.1.9
0:  autoprefixer-rails (5.1.9) from /home/vagrant/.gem/ruby/specifications/autoprefixer-rails-5.1.9.gemspec
Using debug_inspector 0.0.2
0:  debug_inspector (0.0.2) from /home/vagrant/.gem/ruby/specifications/debug_inspector-0.0.2.gemspec
Using binding_of_caller 0.7.2
0:  binding_of_caller (0.7.2) from /home/vagrant/.gem/ruby/specifications/binding_of_caller-0.7.2.gemspec
Using sass 3.4.13
0:  sass (3.4.13) from /home/vagrant/.gem/ruby/specifications/sass-3.4.13.gemspec
Using bootstrap-sass 3.3.4.1
0:  bootstrap-sass (3.3.4.1) from /home/vagrant/.gem/ruby/specifications/bootstrap-sass-3.3.4.1.gemspec
Using builder 3.2.2
0:  builder (3.2.2) from /home/vagrant/.gem/ruby/specifications/builder-3.2.2.gemspec
Using hitimes 1.2.2
0:  hitimes (1.2.2) from /home/vagrant/.gem/ruby/specifications/hitimes-1.2.2.gemspec
Using timers 4.0.1
0:  timers (4.0.1) from /home/vagrant/.gem/ruby/specifications/timers-4.0.1.gemspec
Using celluloid 0.16.0
0:  celluloid (0.16.0) from /home/vagrant/.gem/ruby/specifications/celluloid-0.16.0.gemspec
Using chronic 0.10.2
0:  chronic (0.10.2) from /home/vagrant/.gem/ruby/specifications/chronic-0.10.2.gemspec
Using chunky_png 1.3.4
0:  chunky_png (1.3.4) from /home/vagrant/.gem/ruby/specifications/chunky_png-1.3.4.gemspec
Using coderay 1.1.0
0:  coderay (1.1.0) from /home/vagrant/.gem/ruby/specifications/coderay-1.1.0.gemspec
Using coffee-script-source 1.9.1.1
0:  coffee-script-source (1.9.1.1) from /home/vagrant/.gem/ruby/specifications/coffee-script-source-1.9.1.1.gemspec
Using coffee-script 2.4.1
0:  coffee-script (2.4.1) from /home/vagrant/.gem/ruby/specifications/coffee-script-2.4.1.gemspec
Using commonjs 0.2.7
0:  commonjs (0.2.7) from /home/vagrant/.gem/ruby/specifications/commonjs-0.2.7.gemspec
Using multi_json 1.11.0
0:  multi_json (1.11.0) from /home/vagrant/.gem/ruby/specifications/multi_json-1.11.0.gemspec
Using compass-core 1.0.3
0:  compass-core (1.0.3) from /home/vagrant/.gem/ruby/specifications/compass-core-1.0.3.gemspec
Using compass-import-once 1.0.5
0:  compass-import-once (1.0.5) from /home/vagrant/.gem/ruby/specifications/compass-import-once-1.0.5.gemspec
Using rb-fsevent 0.9.4
0:  rb-fsevent (0.9.4) from /home/vagrant/.gem/ruby/specifications/rb-fsevent-0.9.4.gemspec
Using ffi 1.9.8
0:  ffi (1.9.8) from /home/vagrant/.gem/ruby/specifications/ffi-1.9.8.gemspec
Using rb-inotify 0.9.5
0:  rb-inotify (0.9.5) from /home/vagrant/.gem/ruby/specifications/rb-inotify-0.9.5.gemspec
Using compass 1.0.3
0:  compass (1.0.3) from /home/vagrant/.gem/ruby/specifications/compass-1.0.3.gemspec
Using curb 0.8.8
0:  curb (0.8.8) from /home/vagrant/.gem/ruby/specifications/curb-0.8.8.gemspec
Using docile 1.1.5
0:  docile (1.1.5) from /home/vagrant/.gem/ruby/specifications/docile-1.1.5.gemspec
Using eventmachine 1.0.7
0:  eventmachine (1.0.7) from /home/vagrant/.gem/ruby/specifications/eventmachine-1.0.7.gemspec
Using http_parser.rb 0.6.0
0:  http_parser.rb (0.6.0) from /home/vagrant/.gem/ruby/specifications/http_parser.rb-0.6.0.gemspec
Using em-websocket 0.5.1
0:  em-websocket (0.5.1) from /home/vagrant/.gem/ruby/specifications/em-websocket-0.5.1.gemspec
Using erubis 2.7.0
0:  erubis (2.7.0) from /home/vagrant/.gem/ruby/specifications/erubis-2.7.0.gemspec
Using expression_parser 0.9.0
0:  expression_parser (0.9.0) from /home/vagrant/.gem/ruby/specifications/expression_parser-0.9.0.gemspec
Using favicon_maker 1.3
0:  favicon_maker (1.3) from /home/vagrant/.gem/ruby/specifications/favicon_maker-1.3.gemspec
Using mini_portile 0.6.0
0:  mini_portile (0.6.0) from /home/vagrant/.gem/ruby/specifications/mini_portile-0.6.0.gemspec
Using nokogiri 1.6.6.2
0:  nokogiri (1.6.6.2) from /home/vagrant/.gem/ruby/specifications/nokogiri-1.6.6.2.gemspec
Using loofah 2.0.1
0:  loofah (2.0.1) from /home/vagrant/.gem/ruby/specifications/loofah-2.0.1.gemspec
Using sax-machine 1.3.1
0:  sax-machine (1.3.1) from /home/vagrant/.gem/ruby/specifications/sax-machine-1.3.1.gemspec
Using feedjira 1.6.0
0:  feedjira (1.6.0) from /home/vagrant/.gem/ruby/specifications/feedjira-1.6.0.gemspec
Using bundler 1.7.8
0:  bundler (1.7.8) from /usr/share/gems/specifications/bundler-1.7.8.gemspec
Using uber 0.0.13
0:  uber (0.0.13) from /home/vagrant/.gem/ruby/specifications/uber-0.0.13.gemspec
Using hooks 0.4.0
0:  hooks (0.4.0) from /home/vagrant/.gem/ruby/specifications/hooks-0.4.0.gemspec
Using listen 2.10.0
0:  listen (2.10.0) from /home/vagrant/.gem/ruby/specifications/listen-2.10.0.gemspec
Using padrino-support 0.12.5
0:  padrino-support (0.12.5) from /home/vagrant/.gem/ruby/specifications/padrino-support-0.12.5.gemspec
Using tilt 1.4.1
0:  tilt (1.4.1) from /home/vagrant/.gem/ruby/specifications/tilt-1.4.1.gemspec
Using padrino-helpers 0.12.5
0:  padrino-helpers (0.12.5) from /home/vagrant/.gem/ruby/specifications/padrino-helpers-0.12.5.gemspec
Using rack 1.6.0
0:  rack (1.6.0) from /home/vagrant/.gem/ruby/specifications/rack-1.6.0.gemspec
Using rack-test 0.6.3
0:  rack-test (0.6.3) from /home/vagrant/.gem/ruby/specifications/rack-test-0.6.3.gemspec
Using thor 0.19.1
0:  thor (0.19.1) from /usr/share/gems/specifications/thor-0.19.1.gemspec
Using middleman-core 3.3.10
0:  middleman-core (3.3.10) from /home/vagrant/.gem/ruby/specifications/middleman-core-3.3.10.gemspec
Using font-awesome-middleman 4.2.3
0:  font-awesome-middleman (4.2.3) from /home/vagrant/.gem/ruby/specifications/font-awesome-middleman-4.2.3.gemspec
Using haml 4.0.6
0:  haml (4.0.6) from /home/vagrant/.gem/ruby/specifications/haml-4.0.6.gemspec
Using hike 1.2.3
0:  hike (1.2.3) from /home/vagrant/.gem/ruby/specifications/hike-1.2.3.gemspec
Using htmlentities 4.3.3
0:  htmlentities (4.3.3) from /home/vagrant/.gem/ruby/specifications/htmlentities-4.3.3.gemspec
Using icalendar 1.5.4
0:  icalendar (1.5.4) from /home/vagrant/.gem/ruby/specifications/icalendar-1.5.4.gemspec
Using kramdown 1.6.0
0:  kramdown (1.6.0) from /home/vagrant/.gem/ruby/specifications/kramdown-1.6.0.gemspec
Using less 2.6.0
0:  less (2.6.0) from /home/vagrant/.gem/ruby/specifications/less-2.6.0.gemspec
Using libv8 3.16.14.7
0:  libv8 (3.16.14.7) from /home/vagrant/.gem/ruby/specifications/libv8-3.16.14.7-x86_64-linux.gemspec
Using method_source 0.8.2
0:  method_source (0.8.2) from /home/vagrant/.gem/ruby/specifications/method_source-0.8.2.gemspec
Using sprockets 2.12.3
0:  sprockets (2.12.3) from /home/vagrant/.gem/ruby/specifications/sprockets-2.12.3.gemspec
Using sprockets-helpers 1.1.0
0:  sprockets-helpers (1.1.0) from /home/vagrant/.gem/ruby/specifications/sprockets-helpers-1.1.0.gemspec
Using sprockets-sass 1.3.1
0:  sprockets-sass (1.3.1) from /home/vagrant/.gem/ruby/specifications/sprockets-sass-1.3.1.gemspec
Using middleman-sprockets 3.4.2
0:  middleman-sprockets (3.4.2) from /home/vagrant/.gem/ruby/specifications/middleman-sprockets-3.4.2.gemspec
Using uglifier 2.7.1
0:  uglifier (2.7.1) from /home/vagrant/.gem/ruby/specifications/uglifier-2.7.1.gemspec
Using middleman 3.3.10
0:  middleman (3.3.10) from /home/vagrant/.gem/ruby/specifications/middleman-3.3.10.gemspec
Using middleman-blog 3.5.3
0:  middleman-blog (3.5.3) from /home/vagrant/.gem/ruby/specifications/middleman-blog-3.5.3.gemspec
Using net-ssh 2.9.2
0:  net-ssh (2.9.2) from /home/vagrant/.gem/ruby/specifications/net-ssh-2.9.2.gemspec
Using net-sftp 2.1.2
0:  net-sftp (2.1.2) from /home/vagrant/.gem/ruby/specifications/net-sftp-2.1.2.gemspec
Using ptools 1.3.2
0:  ptools (1.3.2) from /home/vagrant/.gem/ruby/specifications/ptools-1.3.2.gemspec
Using middleman-deploy 1.0.0
0:  middleman-deploy (1.0.0) from /home/vagrant/.gem/ruby/specifications/middleman-deploy-1.0.0.gemspec
Using middleman-favicon-maker 3.7
0:  middleman-favicon-maker (3.7) from /home/vagrant/.gem/ruby/specifications/middleman-favicon-maker-3.7.gemspec
Using rack-livereload 0.3.15
0:  rack-livereload (0.3.15) from /home/vagrant/.gem/ruby/specifications/rack-livereload-0.3.15.gemspec
Using middleman-livereload 3.4.2
0:  middleman-livereload (3.4.2) from /home/vagrant/.gem/ruby/specifications/middleman-livereload-3.4.2.gemspec
Using slop 3.6.0
0:  slop (3.6.0) from /home/vagrant/.gem/ruby/specifications/slop-3.6.0.gemspec
Using pry 0.10.1
0:  pry (0.10.1) from /home/vagrant/.gem/ruby/specifications/pry-0.10.1.gemspec
Using middleman-pry 0.0.4
0:  middleman-pry (0.0.4) from /home/vagrant/.gem/ruby/specifications/middleman-pry-0.0.4.gemspec
Using rouge 1.8.0
0:  rouge (1.8.0) from /home/vagrant/.gem/ruby/specifications/rouge-1.8.0.gemspec
Using middleman-syntax 2.0.0
0:  middleman-syntax (2.0.0) from /home/vagrant/.gem/ruby/specifications/middleman-syntax-2.0.0.gemspec
Using oj 2.12.2
0:  oj (2.12.2) from /home/vagrant/.gem/ruby/specifications/oj-2.12.2.gemspec
Using open-uri-cached 0.0.5
0:  open-uri-cached (0.0.5) from /home/vagrant/.gem/ruby/specifications/open-uri-cached-0.0.5.gemspec
Using pry-stack_explorer 0.4.9.2
0:  pry-stack_explorer (0.4.9.2) from /home/vagrant/.gem/ruby/specifications/pry-stack_explorer-0.4.9.2.gemspec
Using rails-assets-jquery 1.11.3
0:  rails-assets-jquery (1.11.3) from /home/vagrant/.gem/ruby/specifications/rails-assets-jquery-1.11.3.gemspec
Using rails-assets-moment 2.10.2
0:  rails-assets-moment (2.10.2) from /home/vagrant/.gem/ruby/specifications/rails-assets-moment-2.10.2.gemspec
Using rails-assets-bootstrap-sortable 1.11.1
0:  rails-assets-bootstrap-sortable (1.11.1) from /home/vagrant/.gem/ruby/specifications/rails-assets-bootstrap-sortable-1.11.1.gemspec
Using rails-assets-fullcalendar 2.4.0
0:  rails-assets-fullcalendar (2.4.0) from /home/vagrant/.gem/ruby/specifications/rails-assets-fullcalendar-2.4.0.gemspec
Using rails-assets-momentjs 2.10.6
0:  rails-assets-momentjs (2.10.6) from /home/vagrant/.gem/ruby/specifications/rails-assets-momentjs-2.10.6.gemspec
Using ref 1.0.5
0:  ref (1.0.5) from /home/vagrant/.gem/ruby/specifications/ref-1.0.5.gemspec
Using stringex 2.5.2
0:  stringex (2.5.2) from /home/vagrant/.gem/ruby/specifications/stringex-2.5.2.gemspec
Using therubyracer 0.12.2
0:  therubyracer (0.12.2) from /home/vagrant/.gem/ruby/specifications/therubyracer-0.12.2.gemspec
Using unf_ext 0.0.6
0:  unf_ext (0.0.6) from /home/vagrant/.gem/ruby/specifications/unf_ext-0.0.6.gemspec
Using unf 0.1.4
0:  unf (0.1.4) from /home/vagrant/.gem/ruby/specifications/unf-0.1.4.gemspec
Using twitter-text 1.11.0
0:  twitter-text (1.11.0) from /home/vagrant/.gem/ruby/specifications/twitter-text-1.11.0.gemspec
Using wikicloth 0.8.3
0:  wikicloth (0.8.3) from /home/vagrant/.gem/ruby/specifications/wikicloth-0.8.3.gemspec
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
bundler: command not found: middleman
Install missing gem executables with `bundle install`

That's _after_ I executed setup.sh.

**Comment by booxter** [comment] 2016-03-11 12:11
export PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.gem/ruby/gems/middleman-core-3.3.10/bin/ helped.

**Comment by rbowen** [comment] 2016-03-14 13:04
So, this is fixed now?

**Comment by booxter** [comment] 2016-03-14 13:12
I would say it's a workaround only, it should have worked without it, as per bundler manual page.

**Comment by rbowen** [comment] 2016-03-14 13:15
Garrett, can you have a look at this, and see whether this is something fixable in either setup or run-server?

**Comment by garrett** [comment] 2016-03-21 13:24
What distro is this being attempted on? Fedora, RHEL, CentOS, etc.…?

(If `bundle install` works, `bundle exec middleman` really should too.)

**Comment by booxter** [comment] 2016-03-21 13:25
-bash-4.2$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

**Comment by garrett** [comment] 2016-03-21 14:40
Meanwhile, I've tested in a Fedora 23 Docker container (so it doesn't get more barebones than this) and found that the following packages, in addition to those in `setup.sh` are also needed to be able to build everything with bundler: `sudo rubygem-bundler make redhat-rpm-config tar`.

I'll try doing the same in a CentOS Docker container now.

**Comment by garrett** [comment] 2016-03-21 15:10
It seems that CentOS needs these RPMs to build the gems:

`sudo rubygem-bundler make tar ruby-devel gcc libcurl-devel gcc-g++ zlib-devel patch`

(Also, both need `git` as well, for what should be obvious reasons.)

Both Fedora and CentOS install a number of these either as default or as dependencies for the packges in `setup.sh` — but the script should probably be a little more explicit to ensure the appropriate packages are added regardless of the flavor of the distro (workstation, server, cloud, docker, etc.).

However, once I add the RPMs for Fedora or CentOS, both run the script fine without messing around with any environment variable... so I cannot reproduce the issue here. 

(Next step would be running this in a CentOS VM instead of a container, I suppose.)

**Comment by garrett** [comment] 2016-03-21 15:16
It should be noted that a long while ago, I did make a cross-distro setup script. Last week, I added it as a gist @ https://gist.github.com/garrett/b74725840209e3875eda

_Note: It does also contain a way to run this all in Docker too. The `Dockerfile` references Debian, as this was for the brand-new GCC website I made, but isn't used because it wasn't written in Bash, checked into CVS, and licensed under the GPL. (It was Ruby + git, under the GPL-compatible MIT license, all of which were declared fine at the start of the project.)_

Perhaps it might be time to look into implementing this cross-distro solution? Even possibly with Docker support? (At the time of writing this Dockerfile, Docker wasn't included in distros yet, and it named-clashed with the Window Maker widget from many years ago.)

**Comment by garrett** [comment] 2016-03-21 15:21
https://gist.githubusercontent.com/garrett/b74725840209e3875eda/raw/36877ea7599094a6b2e43409c8ac75b306c50652/setup.sh is the most important file relevant to this discussion. (`setup.sh`)

As there have been a new versions of Fedora and CentOS released since then, it'd need to be updated and tested.

I'm not sure how to fix the problem in question, but my above posts should (most likely) make everything work in all the flavors of recent versions of CentOS and Fedora.

**Comment by ununseptium** [comment] 2016-06-10 19:41
I guess this is a good place to hook my thoughts into the build process. I know you're all linux guys and that quite awesome and such but why on earth do you decide to rely on a linux based build process even while using ruby? I just wanted to contribute some things and well ... i was kinda irritated by the setup.sh and all the build thingies you use.

To clarify some things, i am not a linux expert and obviously you must have a good reason for this, but people like me (using os x by default) can't just run and go. Which makes me sad and kinda frustrated.

My actual question now is, why is this how it is?

And if i am completely wrong and i can actually (somehow) build it easily (i'm not speaking of vm's) on os x without doing super squishy things, please tell me i am really curious.

(I am not salty, my english is just not good enough to express more layers than this 😭)

**Comment by rbowen** [comment] 2016-06-10 20:16
The website, and the tools to run it, are a completely separate thing from the RDO developer environment itself.

Now, having said that, I don't know what you mean by super squishy things, and I don't have an OSX machine to test with. Can you elaborate?

**Comment by ununseptium** [comment] 2016-06-10 20:33
With "super squishy things" i mean, to somehow get this ruby environment to work on OS X by working around the dependency resolution of the linux package managers.

And exactly thats the point i don't get, you say that the website is completely separate from the RDO dev environment but still require a linux environment. That doesn't make sense for me.

I just would like to use my OS X tools to contribute to this project, thats all 😢

**Comment by rbowen** [comment] 2016-06-10 20:49
Working on the website does not require anything other than a text editor. All of the content is in markdown, which you can edit in whatever text editor you want. You can also edit documents directly on Github by clicking on the "edit on Github" link in the top right corner of each page on the website.

If you *want* to run a copy of the website, that's what the run-server script is for, but it's not a requirement, and it's completely separate from what you'd need to do to work on the RDO code itself - that's what I mean when I say that it's a separate thing.

Here's a doc on setting up Ruby gems on OSX - https://gorails.com/setup/osx/10.10-yosemite - but, like I said, I don't have access to an osx machine, so I don't know what additional work would be involved in setting up the mirror website stuff.

**Comment by ununseptium** [comment] 2016-06-10 21:13
I know. I already did contribute some "text based" stuff but now i wanted to build the website and since i am not so deep into ruby i was a bit frustrated that there were only a build script for linux. But if you say it's not a requirement i'll try to set my machine up to run the website and contribute a few things. 

Thanks for your answers and sorry for kinda interrupting this comment section.

**Comment by cbrown2** [comment] 2017-06-20 12:06
I have updated the README instructions in PR #948

**Comment by snecklifter** [comment] 2017-08-01 13:50
@rbowen I guess this can be closed now that the README has been updated?

**Comment by rbowen** [comment] 2017-08-01 15:10
Yes. Thanks, @snecklifter

**Closed by rbowen** 2017-08-01 15:10 UTC
