### ISSUE TITLE
beta.rdoproject.org ends up on ask.openstack.org

### ISSUE THREAD

**Issue by apevec** [redhat-openstack/website#476] opened 2016-03-17 20:55 UTC

**Comment by rbowen** [comment] 2016-03-31 21:02
I'm unclear where it *should* go.

The DNS zone contains:

rcip                    IN      A       46.231.133.18
beta                    IN      CNAME   rcip
rpmfactory.beta         IN      A       46.231.133.35


The last of these appears to go somewhere useful, but neither rcip nor beta go anywhere useful.

Can someone suggest what the expected behavior here is?

**Comment by apevec** [comment] 2016-04-01 13:25
rpmfactory.beta.rdoproject.org is correct, it's testing instance of future production RDO development platform based on upstream infra tools (gerrit, jenkinks, zuul etc.) which will be available on review.rdoproject.org

beta should be probably kept and point to the staging environment where stuff like middleman v4 upgrade is tested?

**Comment by apevec** [comment] 2016-04-01 13:44
And rcip is the current hosting location for the production website:

```
www.rdoproject.org is an alias for rcip.rdoproject.org.
rcip.rdoproject.org has address 46.231.133.18
```

**Comment by rbowen** [comment] 2016-04-01 13:49
Oh, I see. So it's just failing because of the SSL certificate issue. That's ... frustrating.

**Comment by hguemar** [comment] 2016-05-03 15:23
Update or should we close it?

**Comment by hguemar** [comment] 2016-05-25 09:46
No feedback for 3 weeks since last ping, please reopen it if you feel it's not fixed

**Closed by hguemar** 2016-05-25 09:46 UTC
Labels: infra

**Comment by apevec** [comment] 2016-05-25 09:54
Yes, this can be closed. Current situation in DNS is:

www.rdoproject.org is an alias for os1.rdoproject.org.
os1.rdoproject.org has address 209.132.179.87
=> @rbowen @mscherer  so we're hosting production website again in OS1 ?

beta.rdoproject.org is an alias for rcip.rdoproject.org.
rcip.rdoproject.org has address 46.231.133.18
=> 46.231.133.18 is not responding
beta.rdoproject.org would be used for MiddleMan 4 migration, so DNS entry will be updated when that's ready in the meantime it could be removed from DNS ?
